### ISSUE TITLE
wl_pointer.leave() event not sent after getting zxdg_toplevel_v6.resize() request

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#760]
While resizing a window motion events are blocked, but Mir does not send `wl_pointer.leave()`. This behavior is different than wlroots, and appears to violate the protocol:

> If triggered, the surface also will lose the focus of the device (wl_pointer, wl_touch, etc) used for the resize.

I've been testing with weston-terminal which uses v6 shell, but have no reason to believe stable is different. This may or may not have to do with #604.

We also need to test this behavior, which should be easy.

**Comment by wmww** [comment]
Update: can't be tested until #761 is fixed

**Comment by RAOF** [comment]
#761 is now fixed. Chop chop!

**Comment by AlanGriffiths** [comment]
On stable?

**Comment by wmww** [comment]
Yes, still a bug and present on XDG stable. Test: https://github.com/MirServer/wlcs/pull/165

**Comment by wmww** [comment]
Unassigned because I have no plans to work on this in the immediate future and there's no reason I need to be the one to do it. Tests still fail.
